# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: swweeep_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: swweeep_right nice_view_adapter nice_view
  - board: vulpes_majora_v1
    shield: vik_pmw3360_per56
  - board: nice_nano_v2
    shield: vulpes_minora_left
  - board: nice_nano_v2
    shield: vulpes_minora_right
  - board: nice_nano_v2
    shield: vulpes_minora_right vik_cirque_spi
  - board: nice_nano_v2
    shield: vulpes_minora_right vik_pmw3610
  - board: xivik@0.2.0
    shield: vik_vikropad
  - board: xivik@0.3.0
    shield: vik_vikropad
  - board: svlinky@0.1.0
    shield: vik_vikropad
  - board: svlinky@0.2.0
    shield: vik_vikropad
  - board: vikoto
    shield: vik_vikropad
  - board: nice_nano_v2
    shield: settings_reset
